### ISSUE TITLE
camera init error

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#4]
OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
no camera in pos 0
sending to cityIO...
objc[1774]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[1774]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
('got video at: ', <VideoCapture 0x113500950>)
(16, 30, 16)
2019-04-05 15:20:27.058 Python[1772:55548] modalSession has been exited prematurely - check for a reentrant call to endModalSession:

**Comment by RELNO** [comment]
https://github.com/taspinar/twitterscraper/issues/102#issuecomment-373937895 might help: `It seems that this results from the specific Python version which is being used in MacOS 10.13 High Sierra.`

**Comment by agrignard** [comment]
new message error with mac os mojave 

`````
OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
no camera in pos 0
objc[1164]: +[NSValue initialize] may have been in progress in another thread when fork() was called.
objc[1164]: +[NSValue initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
('got video at: ', <VideoCapture 0x10e6ab950>)
Traceback (most recent call last):
  File "./run.py", line 89, in <module>
    modules.scanner_function(multiprocess_shared_dict)
  File "/Users/cityscope/Documents/GitHub/CS_Scanner_Python/modules.py", line 109, in scanner_function
    keystone_points_array, video_resolution_x, video_resolution_y)
  File "/Users/cityscope/Documents/GitHub/CS_Scanner_Python/modules.py", line 433, in create_user_intreface
    -video_resolution_y, video_resolution_y, dont_return_on_ui)
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window_QT.cpp:1223: error: (-27:Null pointer) Max value of the slider must be bigger than 0 in function 'addSlider2'

``````

**Comment by RELNO** [comment]
https://github.com/CityScope/CS_Scanner_Python/releases/tag/2.3 should solve it as most QT elements are not used. Open again if persist.

**Comment by agrignard** [comment]
I tried with the current gihub version (which I guess is similar to the 2.3 release)

However I still have this issue when trying to run the scanner

''''
##################################################

CityScope Python Scanner
Keystone, decode and send over UDP/HTTTP a 2d array
of uniquely tagged LEGO array

##################################################


('getting setting for:', 'table')
[416.0, 236.0, 902.0, 236.0, 307.0, 582.0, 1126.0, 582.0]
OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
no camera in pos 0
objc[1681]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[1681]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
('got video at: ', <VideoCapture 0x11c611390>)
''''

**Comment by RELNO** [comment]
I think we're now narrowed to one issue (the other one was the qt ui).
This might relate to multithreading block by the OS. Can you please try the solution here: https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

**Comment by agrignard** [comment]
It seems a bit better with this trick about multi threading (maybe need to be documented for Mac OS user)

however I still have trouble to launch it

''''
('getting setting for:', 'table')
[416.0, 236.0, 902.0, 236.0, 307.0, 582.0, 1126.0, 582.0]
<Response [200]>
('\n', 'sent at: ', datetime.datetime(2019, 6, 12, 11, 26, 52, 41941))
OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
no camera in pos 0
('got video at: ', <VideoCapture 0x11b07f390>)
<Response [200]>
('\n', 'sent at: ', datetime.datetime(2019, 6, 12, 11, 26, 57, 229685))
''''

See image below 

![Screen Shot 2019-06-12 at 11 27 55 AM](https://user-images.githubusercontent.com/3928502/59364709-485e4000-8d05-11e9-8ad3-84029242f42d.png)

**Comment by agrignard** [comment]
OK I finally realize that my default python was python2... seems to work with python3

**Comment by agrignard** [comment]
new error on. a new Mac mini using Mojave when running the scanning

''''
citysciences-Mac-mini-6:CS_Scanner_Python cityscience$ python3 keystone.py
<VideoCapture 0x7f87182140b0>
select 4 points, by double clicking on each of them in the order: 
	up right, up left, bottom right, bottom left.
Traceback (most recent call last):
  File "keystone.py", line 130, in <module>
    if selectFourPoints():
  File "keystone.py", line 105, in selectFourPoints
    cv2.imshow('canvas', FRAME)
cv2.error: OpenCV(3.4.5) /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp:358: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
''''

**Comment by agrignard** [comment]
maybe this can help
https://stackoverflow.com/questions/45964751/python3-opencv-cv2-error-215-unable-to-show-captured-image

**Comment by RELNO** [comment]
on first use of webcam, approve access to camera in Terminal.
